### ISSUE TITLE
Add localizations dependencies

### ISSUE THREAD

**Issue by steinmetz** [GJJ2019/mason_bricks#3]
Hi,

I was testing your bricks for creating a new project and I think it would be nice to add the localizations dependencies here:
https://github.com/GJJ2019/mason_bricks/blob/60832e599bc37bb8aa54c3c7b3ce12ebcaea8cf3/bricks/riverpod_project/__brick__/pubspec.yaml#L41
```
    flutter_localizations:
      sdk: flutter
    intl: ^0.17.0
```

What do you think?

**Comment by GJJ2019** [comment]
Thank you for filling this issue.
I have publish v-0.1.0+4 with this fixes
